# Generated by Django 4.0.8 on 2023-01-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_url', models.CharField(max_length=200)),
                ('action_name', models.CharField(max_length=100)),
                ('town_id', models.IntegerField()),
                ('building_id', models.CharField(max_length=100)),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_url', models.CharField(max_length=200)),
                ('action_name', models.CharField(max_length=100)),
                ('farm_town_id', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('option', models.IntegerField()),
                ('town_id', models.IntegerField()),
            ],
        ),
    ]
