# Generated by Django 4.0.8 on 2023-01-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_town_alter_claimorder_town_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimorder',
            name='town_id',
            field=models.IntegerField(),
        ),
    ]
